# Pregunta 1.

* Imprima la suma de las matrices A y B

$$ A =
\left(\begin{array}{cc} 
1 & 2\\
3 & 4\\
5 & 6
\end{array}\right) + B =
\left(\begin{array}{cc} 
6 & 5\\
4 & 3\\
2 & 1 
\end{array}\right)
$$ 

In [2]:
# Respuesta 1.
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
b=np.array([[6,5],[4,3],[2,1]])
print(a+b)




[[7 7]
 [7 7]
 [7 7]]


# Pregunta 2

* Imprima la suma de matriz + Escalar.

$$ M =
\left(\begin{array}{cc} 
6 & 3\\
9 & 5\\
4 & 8
\end{array}\right) + N =
\left(\begin{array}{cc} 
2.5 \\ 
\end{array}\right)
$$ 

In [3]:
# Respuesta 2.
m=np.array([[6,3],[9,5],[4,8]])
n=2.5
print(m+n)


[[ 8.5  5.5]
 [11.5  7.5]
 [ 6.5 10.5]]


# Pregunta 3.

* Imprima la  transpuesta de la siguiente matriz  $J$  es decir $J^t$. 

$$ J =
\left(\begin{array}{cc} 
9 & 2 & 3\\
3 & 7 & 4 \\
5 & 6 & 9
\end{array}\right) 
$$ 

In [4]:
# Respuesta 3.
'su còdigo aqui'
import numpy as np
j=np.array([[9,2,3],[3,7,4],[5,6,9]])
jt=j.T
print(jt)

[[9 3 5]
 [2 7 6]
 [3 4 9]]


# Pregunta 4.

* Para la matriz $J^t$, calcule su transpuesta para obtener la matriz original J.  

$$ J =
\left(\begin{array}{cc} 
9 & 2 & 3\\
3 & 7 & 4 \\
5 & 6 & 9
\end{array}\right) 
$$ 

In [5]:
# Respuesta 4.
'su còdigo aqui'
print(jt.T)

[[9 2 3]
 [3 7 4]
 [5 6 9]]


# Pregunta 5.

* ¿ Cuales son los valores faltantes ? (en el orden en que aparecen las matrices)

$$
\left(\begin{array}{cc} 
? & 2\\
0 & 2
\end{array}\right)
\left(\begin{array}{cc} 
1 & 0 \\ 
1 & ? 
\end{array}\right)
$$ 

 * para que la respuesta sea:
$
\left(
 \begin {array}{ll} 
1 & 0 \\
0   & 0
\end{array}
\right)
$

- [ A ] = 1 y 1
- [ B ] = 0 y 1
- [ C ] = 1 y 0
- [ D ] = 0 y 0

* Imprima el resultado y la respuesta.

In [9]:
# Respuesta 4.
'su còdigo aqui'

import numpy as np

# creacion de matrices 
A = np.array([[1,2],[0,2]])
d = np.array([[1,0],[1,0]])

# calculo de producto entre matrices
C = A * d
# imprimir la respuesta
print('la respuesgta es la C:',"\n", C)

la respuesgta es la C: 
 [[1 0]
 [0 0]]


# Pregunta 6.
* ¿ Cual es Producto Punto de las matrices $L$ y $K$ = : ?


$$ L =
\left(\begin{array}{cc} 
3 & 5 \\
7 & 1 \\
\end{array}\right) K =
\left(\begin{array}{cc} 
3 & 12  \\
6 & 4  \\
\end{array}\right)
$$ 

In [0]:
L=np.array([[3,5],[7,1]])
K=np.array([[3,12],[6,4]])
print(L.dot(K))

[[39 56]
 [27 88]]


# Pregunta 7.

* ¿ Cual es el determinante de la siguiente matriz ? (imprima la respuesta)

$
\left(
\begin {array}{ll} 
1 & 2 & 0 \\
1 & 2 & 0 \\
0 & 1 & 1 \\
\end{array}
\right)
$

- [ A ] = 1 
- [ B ] = 0 
- [ C ] = 5
- [ D ] = -5



In [12]:
# Respuesta 3.
'su còdigo aqui'

import numpy as np
D = np.array([[1,2,0],[1,2,0], [0,1,1] ])

determinant = np.linalg.det(D)

print('la respuesgta es la B:', determinant)

la respuesgta es la B: 0.0


# Pregunta 8.

* ¿ Cual es el determinante de la siguiente matriz ? (imprima la respuesta)

$
\left(
\begin {array}{ll} 
0 & 1 & 1 \\
1 & 0 & 0 \\
0 & 0 & 1 \\
\end{array}
\right)
$

- [ A ] = 0 
- [ B ] = -1 
- [ C ] = 3
- [ D ] = 1


In [0]:
import numpy as np
F = np.array([[0,1,1],[1,0,0], [0,0,1] ])

np.linalg.det(F)

-1.0